language: ruby
rvm:
  - 2.2.0

sudo: false
cache: bundler
git:
  submodules: false

script: ./go ci_build

after_script: bash ./script/continua11y.sh

notifications:
  email:
    recipients:
      - eric.mill@gsa.gov
      - hillary.hartley@gsa.gov
      - gregory.boone@gsa.gov
    on_success: change
    on_failure: change

branches:
  only:
    - staging
    - production

env:
  global:
    - RUN_SCRIPT="bundle exec jekyll serve --detach"
    - KILL_SCRIPT="pkill -f jekyll"
    - USE_SITEMAP=false
    - PORT=4000
    - CONTINUA11Y="continua11y.herokuapp.com"